# [review:need-review] PHASE-03/135
# summary: wire types of the agent's activity — a batch of intervals capped at 500, an interval read back with its generated duration and the display name of its application, the day's roll-up per application, and the mode of a date with who decided it
"""
Wire types of the measured activity.

**Приложение называется bundle id, не числом.** Every incoming interval names
`com.microsoft.VSCode`; the catalogue id is an answer, never a question. The
agent has the bundle id and nothing else, and asking it to carry server-side ids
would make the first request after a restore of the database wrong.

**Заголовок приезжает уже обработанным.** `title_source` says what the mac did
with it — `full`, `masked` or `dropped` — and the server does not re-derive it.
Applying the policy on the machine is what keeps a forbidden title off the
network; a server-side second opinion would arrive too late to matter.

**Длительность не присылается.** `duration_seconds` is generated by postgres from
the two ends, and there is deliberately no field for it here: a client that could
state it could state it wrong.
"""

from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models.activity import (
    ACTIVITY_SOURCE_AGENT,
    ACTIVITY_SOURCES,
    DAY_MODE_KINDS,
    TITLE_DROPPED,
    TITLE_SOURCES,
)

# Потолок пачки. Не вкус: агент шлёт раз в несколько минут, пачка в пятьсот
# интервалов покрывает многочасовой офлайн, а запрос, который может быть сколь
# угодно большим, однажды придёт таким.
MAX_BATCH_INTERVALS = 500


def _one_of(value: str, allowed: tuple[str, ...], field_name: str) -> str:
    """Membership check shared by every vocabulary field, error text included."""
    if value not in allowed:
        raise ValueError(f"{field_name} must be one of: {', '.join(allowed)}")
    return value


class ActivityIntervalIn(BaseModel):
    """One interval, as the agent sends it."""

    model_config = ConfigDict(extra="forbid")

    bundle_id: str | None = Field(
        default=None,
        max_length=200,
        description=(
            "Приложение. Неизвестное — 422 со своим именем в теле: каталог "
            "пополняется решением, а не потоком данных. Пусто у ручной записи"
        ),
    )
    started_at: datetime
    ended_at: datetime
    local_date: date = Field(
        description="Календарь, который прожил человек; сервер судит по своей границе суток"
    )
    utc_offset_minutes: int = 0
    title: str | None = Field(
        default=None, description="Уже нормализован на маке; сервер его не трогает"
    )
    title_source: str = Field(
        default=TITLE_DROPPED, description=f"Одно из: {', '.join(TITLE_SOURCES)}"
    )
    idle_seconds: int = Field(default=0, ge=0)
    switch_count: int = Field(default=0, ge=0)
    source: str = ACTIVITY_SOURCE_AGENT
    note: str | None = None

    @field_validator("title_source")
    @classmethod
    def _check_title_source(cls, value: str) -> str:
        return _one_of(value, TITLE_SOURCES, "title_source")

    @field_validator("source")
    @classmethod
    def _check_source(cls, value: str) -> str:
        return _one_of(value, ACTIVITY_SOURCES, "source")


class ActivityBatchIn(BaseModel):
    """
    A batch of intervals in one request.

    Whole rather than one by one: the agent glues samples into intervals offline
    and flushes what accumulated, and a request per interval would turn an hour
    without network into hundreds of requests when it comes back.
    """

    model_config = ConfigDict(extra="forbid")

    intervals: list[ActivityIntervalIn] = Field(
        max_length=MAX_BATCH_INTERVALS,
        description=f"Не больше {MAX_BATCH_INTERVALS} интервалов за раз",
    )


class ActivityIntervalResponse(BaseModel):
    """One stored interval, with the duration postgres computed for it."""

    id: int
    source: str
    app_id: int | None
    bundle_id: str | None
    app_name: str | None
    started_at: datetime
    ended_at: datetime
    duration_seconds: int
    local_date: date
    title_source: str
    idle_seconds: int
    switch_count: int
    is_corrected: bool
    note: str | None


class ActivityAppSlice(BaseModel):
    """One application's share of a day, as the day screen lists it."""

    app_id: int | None
    bundle_id: str | None
    app_name: str
    minutes: int


class ActivityBatchResponse(BaseModel):
    """
    What a batch did, and what the markup made of it.

    `intervals_written` counts rows the batch touched — the same number on a
    re-send, because the natural key folds a repeat onto the row it already
    wrote. `classified_days` is how many days the markup restated afterwards, so
    a caller can tell «приняли, но не разметили» from «разметили».
    """

    intervals_written: int
    classified_days: int


class ActivityDayResponse(BaseModel):
    """Where a day went, by application, plus the intervals it is made of."""

    work_day: date
    mode: str
    total_minutes: int
    apps: list[ActivityAppSlice]
    intervals: list[ActivityIntervalResponse]


class DayModeResponse(BaseModel):
    """
    Which kind of day a date is, and who said so.

    `source` is part of the answer: «выходной по расписанию» and «выходной,
    потому что так решил человек» are the same day and different facts.
    """

    date: date
    kind: str = Field(description=f"Одно из: {', '.join(DAY_MODE_KINDS)}")
    nocode: bool
    source: str


__all__ = [
    "MAX_BATCH_INTERVALS",
    "ActivityAppSlice",
    "ActivityBatchIn",
    "ActivityBatchResponse",
    "ActivityDayResponse",
    "ActivityIntervalIn",
    "ActivityIntervalResponse",
    "DayModeResponse",
]
