// [review:need-review] PHASE-03/147, PHASE-03/148
// summary: the day fixture both day-screen suites render — one day off with its rule, its map and its итог, and one plan the server would answer with; kept out of the two test files so that the desktop shell and the mobile shell are proved against the same day rather than against two that drifted apart

import type { DayDetail, Plan } from '@/lib/api';

export const DAY: DayDetail = {
  day: {
    date: '2026-08-30',
    kind: 'off',
    is_nocode: false,
    opened_at: null,
    last_touched_at: null,
  },
  profile: null,
  rule: {
    id: 2,
    valid_from: '2026-08-17',
    valid_to: null,
    timezone: 'Europe/Berlin',
    day_start_hour: 4,
    work_cap_min: 480,
    work_hard_cap_min: 540,
    work_stop_at: '16:00:00',
    max_work_tasks: 4,
    tasks_required_ratio: '1.00',
    overtime_disqualifies: true,
    workdays: [1, 2, 3, 4, 5],
    nocode_days: [2, 4],
    required_anchors: ['подъём'],
    overtime_lost_min: 600,
    max_study_items: 2,
    wake_at: '06:00:00',
    work_start: '07:45:00',
    review_at: '15:40:00',
    bedtime_max: '22:30:00',
    free_evening_start: '19:10:00',
    free_evening_end: '21:00:00',
    relationship_anchor_required: true,
    relationship_evening_start: '18:30:00',
    relationship_evening_end: '21:00:00',
    days_off: [6, 7],
    hard_edge_kinds: ['anchor', 'hard_point'],
    anchors: ['подъём', 'relationship'],
    verdict_rule: { reason_order: ['overtime', 'anchors', 'tasks'] },
    role_clause_enabled: true,
    role_clause_roles: 'cto,architect',
    note_md: '',
  },
  day_map: {
    rule_set_id: 2,
    edges: [
      { kind: 'wake', label: 'подъём', at: '06:00:00' },
      { kind: 'sport', label: 'спорт', at: null },
      { kind: 'work_start', label: 'старт работы', at: '07:45:00' },
      { kind: 'work_stop', label: 'стоп работы', at: '16:00:00' },
      { kind: 'review', label: 'ревью', at: '15:40:00' },
      { kind: 'bedtime', label: 'отбой', at: '22:30:00' },
    ],
    free_evening: { start: '19:10:00', end: '21:00:00' },
    relationship_evening: { start: '18:30:00', end: '21:00:00' },
    relationship_anchor_required: true,
    work_cap_min: 480,
    work_hard_cap_min: 540,
    overtime_lost_min: 600,
    work_stop_at: '16:00:00',
    max_work_tasks: 4,
    max_study_items: 2,
    anchors: ['подъём', 'relationship'],
    hard_edge_kinds: ['anchor', 'hard_point'],
    workdays: [1, 2, 3, 4, 5],
    days_off: [6, 7],
    nocode_days: [2, 4],
    verdict_reasons: ['overtime', 'anchors', 'tasks'],
  },
  plan: null,
  has_plan: false,
  marks: [],
  task_counts: { planned: 0, done: 0, failed: 0, skipped: 0, pending: 0 },
  notebook: null,
  anchors: {
    day_date: '2026-08-30',
    anchors: [],
    done: 0,
    total: 0,
    missing: [],
  },
  training: null,
  summary: {
    day_date: '2026-08-30',
    closed: false,
    stage: 'open' as const,
    reviewed_at: null,
    review_skipped: false,
    rule_set_id: 2,
    verdict: null,
    verdict_reason: 'not_closed',
    verdict_override: false,
    verdict_override_note: null,
    anchors_done: 0,
    anchors_total: 0,
    tasks_done: 0,
    tasks_total: 0,
    work_minutes: null,
    streak_after: null,
    wrote_from_scratch: null,
    education_debt: null,
    reviewed_today: null,
    body_md: '',
    missing_data: ['work_minutes'],
    missing_anchors: [],
    source: 'close',
    verdict_origin: 'none' as const,
  },
  work: {
    day_date: '2026-08-30',
    intervals: [],
    // «Не измерено», not zero: the day has no intervals at all.
    work_minutes: null,
    running: false,
  },
};

// A plan as the server answers with one: sections in order, a schedule the
// server measured, and no collisions.
export const PLAN: Plan = {
  id: 'p1',
  day_date: '2026-08-30',
  title: 'План 2026-08-30 (вс)',
  title_marker: null,
  lede: 'Выходной по канону',
  purpose_md: null,
  quarter_goal_id: null,
  counters: [],
  condition_tomorrow: null,
  status: 'active',
  source: 'day-open',
  needs_review: false,
  fallback_reason: null,
  created_at: '2026-08-30T06:00:00Z',
  updated_at: '2026-08-30T06:00:00Z',
  sections: [
    {
      id: 's1',
      ord: 0,
      title: 'Воскресный блок',
      kind: 'personal',
      role_id: null,
      items: [
        {
          id: 'i1',
          parent_id: null,
          ord: 0,
          kind: 'bullet',
          rigidity: 'soft',
          text_md: 'Недельное ретро W35',
          text_plain: 'Недельное ретро W35',
          starts_at: '2026-08-30T09:00:00Z',
          ends_at: '2026-08-30T09:40:00Z',
          window_comment: null,
          code: null,
          done_criterion: null,
          why_md: null,
          plan_md: null,
          external_ref: null,
          extra: {},
          quarter_goal_id: null,
          unlinked_reason: null,
          role_id: null,
          act_kind: null,
          carried_from_item_id: null,
          carry_count: 0,
          children: [],
        },
      ],
    },
  ],
  schedule: [
    {
      item_id: 'i1',
      section_id: 's1',
      code: null,
      text_plain: 'Недельное ретро W35',
      kind: 'bullet',
      rigidity: 'soft',
      starts_at: '2026-08-30T09:00:00Z',
      ends_at: '2026-08-30T09:40:00Z',
      minutes: 40,
      window_comment: null,
    },
  ],
  overlaps: [],
};
