# [review:need-review] PHASE-03/135, PHASE-03/158, PHASE-03/160
# summary: the tables of the macOS agent's theme, straight out of ADR-0019 — `tracked_app` (the catalogue a title policy hangs off, default deny), `title_rule` (privacy of window titles, first match wins), `activity_interval` (the grain: an interval, not a sample, idempotent on `(source, started_at, app_id)`, `duration_seconds` generated by postgres), `day_mode` / `mode_schedule` (which day it is, a manual row overriding the schedule), `agent_heartbeat` and `claude_session`; #158 adds `agent_setting` — the one row the kill switch of window titles lives in; #160 gives a manual interval its `idempotency_key`
"""
The tables the macOS agent writes into.

Written whole rather than one ticket at a time, exactly as ADR-0019 and `#155`
prescribe: one revision for the theme keeps the Alembic chain linear, and every
ticket after it writes code instead of a migration.

Three decisions carry the weight, and the rest is columns.

**Зерно данных — интервал, а не отсчёт.** Adjacent samples of the same app are
glued on the mac; a gap under thirty seconds does not break an interval, it
raises `switch_count`. `uq_activity_interval_natural (source, started_at,
app_id)` is what makes a re-sent batch land on the rows it already wrote, so the
agent stream needs no `Idempotency-Key` at all — the same trick the health
contour uses in `upsert_buckets`.

**Заголовок окна — по умолчанию нет.** `tracked_app.title_policy` defaults to
`drop` and `title_rule` decides the rest, first match winning. The rules live on
the server so they can be edited from the web and survive a reinstall of the
agent, and they are applied *on the mac* so a forbidden title never crosses the
network. `title_source` says out loud what happened to a title rather than
leaving `NULL` to mean two different things.

**Режим дня — строка только когда решил человек.** A day with no `day_mode` row
is whatever `mode_schedule` says about its weekday; a manual row overrides the
schedule for that date and nothing else. Same semantics as
`override=YYYY-MM-DD:on|off` in `~/.claude/nocode/config`, which is where the
rule comes from.

`duration_seconds` is `GENERATED ALWAYS ... STORED`: the length of an interval is
a consequence of its ends, and a column a writer can set is a column that will
one day disagree with them.
"""

from __future__ import annotations

from datetime import date as date_type
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.core.database import Base

# `duration_seconds`, spelled once so the model and the migration cannot drift.
DURATION_EXPR = "EXTRACT(EPOCH FROM (ended_at - started_at))::int"

# Where an interval came from. `manual` rows carry no app and are the reason the
# natural key tolerates a NULL `app_id`: two hand-written records starting at the
# same minute are two records, not a duplicate.
ACTIVITY_SOURCE_AGENT = "agent"
ACTIVITY_SOURCE_MANUAL = "manual"
ACTIVITY_SOURCES: tuple[str, ...] = (ACTIVITY_SOURCE_AGENT, ACTIVITY_SOURCE_MANUAL)

# What became of a window title. Three values rather than «есть/нет», because
# «правило запретило» and «правило оставило домен» are different facts and only
# the first one means the markup has to fall back to `bundle_id` alone.
TITLE_FULL = "full"
TITLE_MASKED = "masked"
TITLE_DROPPED = "dropped"
TITLE_SOURCES: tuple[str, ...] = (TITLE_FULL, TITLE_MASKED, TITLE_DROPPED)

# What a title rule does. Default deny: a title nobody wrote a rule for is
# dropped, so a new application cannot leak a document name by arriving.
TITLE_KEEP = "keep"
TITLE_MASK = "mask"
TITLE_DROP = "drop"
TITLE_POLICIES: tuple[str, ...] = (TITLE_KEEP, TITLE_MASK, TITLE_DROP)

# How a title rule is matched against an interval.
MATCH_BUNDLE_ID = "bundle_id"
MATCH_BUNDLE_PREFIX = "bundle_prefix"
MATCH_TITLE_REGEX = "title_regex"
TITLE_MATCH_KINDS: tuple[str, ...] = (
    MATCH_BUNDLE_ID,
    MATCH_BUNDLE_PREFIX,
    MATCH_TITLE_REGEX,
)

# Which kind of day it is. Orthogonal to `nocode`: вторник is `work` *and*
# `nocode`, and folding the two into one vocabulary would lose that.
MODE_WORK = "work"
MODE_DAYOFF = "dayoff"
MODE_VACATION = "vacation"
MODE_SICK = "sick"
DAY_MODE_KINDS: tuple[str, ...] = (MODE_WORK, MODE_DAYOFF, MODE_VACATION, MODE_SICK)

# Only `work` puts minutes into a role. The rest of the day is lived, not worked,
# and the ADR is explicit that automatic detection of the mode was rejected —
# the evening free block is exactly where it would have been wrong.
WORKING_MODES: frozenset[str] = frozenset({MODE_WORK})

MODE_SOURCE_SCHEDULE = "schedule"
MODE_SOURCE_MANUAL = "manual"
MODE_SOURCES: tuple[str, ...] = (MODE_SOURCE_SCHEDULE, MODE_SOURCE_MANUAL)

# 0 = Sunday … 6 = Saturday, as the schedule is seeded and as the CHECK spells it.
WEEKDAY_MIN = 0
WEEKDAY_MAX = 6


def _in_list(column: str, values: tuple[str, ...]) -> str:
    """`kind IN ('a', 'b')` — spelled once for the model and the migration."""
    joined = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({joined})"


class TrackedApp(Base):
    """
    One application the system knows by name.

    A table rather than an enum for the same reason as `health_metrics`: teaching
    the system a new application must cost a row, not a release. It is also the
    list of whose titles may ever be kept, which is why an unknown `bundle_id`
    is refused by the intake instead of being inserted quietly.
    """

    __tablename__ = "tracked_app"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    bundle_id: Mapped[str] = mapped_column(String(200), unique=True, index=True)
    display_name: Mapped[str] = mapped_column(String(120))
    category: Mapped[str] = mapped_column(String(30), server_default="other")
    title_policy: Mapped[str] = mapped_column(String(10), server_default=TITLE_DROP)
    # Ternary, like `categories.show_in_today`: NULL means «решает режим дня»,
    # which is not the same answer as «это не работа».
    is_work: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    def __repr__(self) -> str:
        return f"<TrackedApp(id={self.id}, bundle_id='{self.bundle_id}')>"


class TitleRule(Base):
    """
    One line of the title privacy policy: «этот заголовок — keep, mask или drop».

    Ordered by `ord`, first match wins, and `id` breaks a tie so the answer is a
    fact rather than a race — the same rule as `role_rule`, for the same reason.

    Stored here and applied on the mac. Both halves matter: on the server they
    can be edited from the web and survive a reinstall, on the mac a forbidden
    title never leaves the machine at all.
    """

    __tablename__ = "title_rule"
    __table_args__ = (
        CheckConstraint(
            _in_list("match_kind", TITLE_MATCH_KINDS), name="ck_title_rule_match_kind"
        ),
        CheckConstraint(
            _in_list("action", TITLE_POLICIES), name="ck_title_rule_action"
        ),
        Index("ix_title_rule_ord", "ord"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    ord: Mapped[int] = mapped_column(Integer)
    match_kind: Mapped[str] = mapped_column(String(20))
    pattern: Mapped[str] = mapped_column(String(300))
    action: Mapped[str] = mapped_column(String(10))
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, server_default="true")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    def __repr__(self) -> str:
        return (
            f"<TitleRule(id={self.id}, ord={self.ord}, "
            f"kind='{self.match_kind}', action='{self.action}')>"
        )


class ActivityInterval(Base):
    """
    One stretch of time one application was in front.

    The grain of the whole theme, and deliberately not the sample: samples are
    glued on the mac, a gap under thirty seconds raises `switch_count` instead of
    starting a new row, and what reaches the server is already an interval.

    `local_date` is the calendar the person lived, carried by the writer rather
    than derived here — the same intake the health contour uses. Which day a
    moment belongs to is `app.core.daytime.local_date`'s question alone, and the
    markup of `#135` asks it there rather than trusting this column blindly.
    """

    __tablename__ = "activity_interval"
    __table_args__ = (
        UniqueConstraint(
            "source",
            "started_at",
            "app_id",
            name="uq_activity_interval_natural",
        ),
        CheckConstraint("ended_at >= started_at", name="ck_activity_interval_forward"),
        CheckConstraint(
            _in_list("source", ACTIVITY_SOURCES), name="ck_activity_interval_source"
        ),
        CheckConstraint(
            _in_list("title_source", TITLE_SOURCES),
            name="ck_activity_interval_title_source",
        ),
        Index("ix_activity_interval_local_date", "local_date"),
        Index("ix_activity_interval_day_app", "local_date", "app_id"),
        Index("ix_activity_interval_task", "plan_task_id"),
        # The read pattern of the markup: every interval of one day in the order
        # it happened. `#135` walks exactly this.
        Index("ix_activity_interval_day_start", "local_date", "started_at"),
        # Идемпотентность ручной записи. Частичный, потому что ключ есть только
        # у неё: естественный ключ её не ловит — `app_id IS NULL`, а NULL в
        # уникальном ключе Postgres различны, и это правильно (два дела в одно
        # окно времени — два дела).
        Index(
            "uq_activity_interval_idempotency",
            "idempotency_key",
            unique=True,
            postgresql_where=text("idempotency_key IS NOT NULL"),
        ),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, index=True)

    source: Mapped[str] = mapped_column(
        String(10), server_default=ACTIVITY_SOURCE_AGENT
    )
    # `RESTRICT`: an application deleted from the catalogue under the intervals
    # that name it would turn measured time into time nobody can attribute.
    # NULL for a manual record, which names no application at all.
    app_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("tracked_app.id", ondelete="RESTRICT"),
        nullable=True,
    )

    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    ended_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    duration_seconds: Mapped[int] = mapped_column(
        Integer, Computed(DURATION_EXPR, persisted=True)
    )

    local_date: Mapped[date_type] = mapped_column(Date)
    utc_offset_minutes: Mapped[int] = mapped_column(Integer, server_default="0")

    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    title_source: Mapped[str] = mapped_column(String(10), server_default=TITLE_DROPPED)

    idle_seconds: Mapped[int] = mapped_column(Integer, server_default="0")
    switch_count: Mapped[int] = mapped_column(Integer, server_default="0")

    plan_task_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    clickup_task_id: Mapped[str | None] = mapped_column(String(40), nullable=True)

    idempotency_key: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Правка постфактум (`#160`): границы подвинуты человеком, а `source`
    # остался прежним. Помечается явно — иначе «я поправил» неотличимо от
    # «агент так посчитал», и доверия к цифре нет ни в одну сторону.
    is_corrected: Mapped[bool] = mapped_column(Boolean, server_default="false")
    corrected_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    note: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    app: Mapped[TrackedApp | None] = relationship()

    def __repr__(self) -> str:
        return (
            f"<ActivityInterval(id={self.id}, day={self.local_date}, "
            f"app_id={self.app_id}, seconds={self.duration_seconds})>"
        )


class ModeSchedule(Base):
    """
    Which kind of day each weekday is by default.

    Seeded from `personal-os/config.md`: пн, вт, ср, пт, сб — `work`; чт и вс —
    `dayoff`; `nocode` on вт and чт. One row per weekday, enforced by the unique
    key rather than by whoever writes.
    """

    __tablename__ = "mode_schedule"
    __table_args__ = (
        CheckConstraint(
            f"weekday BETWEEN {WEEKDAY_MIN} AND {WEEKDAY_MAX}",
            name="ck_mode_schedule_weekday",
        ),
        CheckConstraint(_in_list("kind", DAY_MODE_KINDS), name="ck_mode_schedule_kind"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    # 0 = Sunday … 6 = Saturday.
    weekday: Mapped[int] = mapped_column(SmallInteger, unique=True)
    kind: Mapped[str] = mapped_column(String(10))
    nocode: Mapped[bool] = mapped_column(Boolean, server_default="false")

    def __repr__(self) -> str:
        return f"<ModeSchedule(weekday={self.weekday}, kind='{self.kind}')>"


class DayMode(Base):
    """
    The mode one date was actually in, when a person decided it by hand.

    No row is the normal state: the mode is then whatever `mode_schedule` says
    about that weekday. A row with `source='manual'` overrides the schedule for
    that date and for nothing else — the same semantics as
    `override=YYYY-MM-DD:on|off` in `~/.claude/nocode/config`.

    Автоопределение режима по активности отвергнуто человеком: it would have
    been wrong precisely in the evening free block, where the cost is highest.
    """

    __tablename__ = "day_mode"
    __table_args__ = (
        CheckConstraint(_in_list("kind", DAY_MODE_KINDS), name="ck_day_mode_kind"),
        CheckConstraint(_in_list("source", MODE_SOURCES), name="ck_day_mode_source"),
    )

    date: Mapped[date_type] = mapped_column("date", Date, primary_key=True)
    kind: Mapped[str] = mapped_column(String(10))
    nocode: Mapped[bool] = mapped_column(Boolean, server_default="false")
    source: Mapped[str] = mapped_column(String(10), server_default=MODE_SOURCE_MANUAL)
    decided_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    note: Mapped[str | None] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<DayMode(date={self.date}, kind='{self.kind}')>"


class AgentHeartbeat(Base):
    """
    What one agent says about itself: alive, permitted, how far behind.

    `agent_id` is unique so a second mac is a second row rather than a fight over
    one. `last_error` holds a code and never an exception message — a log line
    with a window title in it would defeat the whole title policy above.
    """

    __tablename__ = "agent_heartbeat"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    agent_id: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    agent_version: Mapped[str] = mapped_column(String(20))
    reported_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    accessibility_granted: Mapped[bool] = mapped_column(Boolean, server_default="false")
    # A switch of its own, separate from the permission: titles can be off while
    # Accessibility is granted, and that is a state a person chooses.
    titles_enabled: Mapped[bool] = mapped_column(Boolean, server_default="false")
    sampling_seconds: Mapped[int] = mapped_column(Integer, server_default="5")
    queue_depth: Mapped[int] = mapped_column(Integer, server_default="0")
    last_flush_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_error: Mapped[str | None] = mapped_column(String(200), nullable=True)

    def __repr__(self) -> str:
        return f"<AgentHeartbeat(agent_id='{self.agent_id}')>"


class ClaudeSession(Base):
    """
    One session of Claude Code, as an aggregate the agent recomputes and re-sends.

    `session_uid` is the natural key of the upsert: a session is appended to all
    day long, so the agent restates it instead of adding to it — the same trick
    as `upsert_buckets`.

    There is no column for message text, and that is the point: content cannot be
    sent even by accident, because the schema has nowhere to put it. Same device
    as the write-only `DailySummaryPlan` in `schemas/daily_summary.py`.
    """

    __tablename__ = "claude_session"
    __table_args__ = (Index("ix_claude_session_local_date", "local_date"),)

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, index=True)

    session_uid: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    cwd: Mapped[str] = mapped_column(String(300))
    git_branch: Mapped[str | None] = mapped_column(String(120), nullable=True)
    local_date: Mapped[date_type] = mapped_column(Date)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    ended_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    assistant_turns: Mapped[int] = mapped_column(Integer, server_default="0")
    user_turns: Mapped[int] = mapped_column(Integer, server_default="0")
    input_tokens: Mapped[int] = mapped_column(BigInteger, server_default="0")
    output_tokens: Mapped[int] = mapped_column(BigInteger, server_default="0")
    cache_read_tokens: Mapped[int] = mapped_column(BigInteger, server_default="0")
    cache_creation_tokens: Mapped[int] = mapped_column(BigInteger, server_default="0")

    models: Mapped[str] = mapped_column(String(200), server_default="")
    goal_title: Mapped[str | None] = mapped_column(String(200), nullable=True)
    cli_version: Mapped[str | None] = mapped_column(String(20), nullable=True)

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    def __repr__(self) -> str:
        return f"<ClaudeSession(uid='{self.session_uid}', day={self.local_date})>"


# The settings are one row on purpose, and this is its id. A CHECK in the table
# refuses any other, so «а если строк две» is not a branch anybody has to write.
SETTINGS_ROW_ID = 1

# Bounds of the sampling interval, spelled once for the model and the migration.
SAMPLING_MIN_SECONDS = 1
SAMPLING_MAX_SECONDS = 600


class AgentSetting(Base):
    """
    What the agent is allowed to do, decided on the server.

    `agent_heartbeat.titles_enabled` is what an agent *reports about itself* and
    cannot be the switch: the agent would rewrite it on every heartbeat, and a
    collection turned off from the web would turn itself back on five seconds
    later. The decision therefore lives here, and `GET /agent/config` hands it to
    the agent.

    One row for the whole system — the user is one, and a single-row table reads
    better than a column bolted onto somebody else's table or an untyped
    key-value store. The row is seeded by the migration, so no reader has to
    carry an «а если строки нет» branch.
    """

    __tablename__ = "agent_setting"
    __table_args__ = (
        CheckConstraint(f"id = {SETTINGS_ROW_ID}", name="ck_agent_setting_single_row"),
        CheckConstraint(
            f"sampling_seconds BETWEEN {SAMPLING_MIN_SECONDS} AND "
            f"{SAMPLING_MAX_SECONDS}",
            name="ck_agent_setting_sampling",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)

    # True by default: the title policy is already default deny (`title_rule`
    # opens with the bans, `tracked_app.title_policy` is `drop`), and a second
    # denial on top of it would mean the allowing rules silently do nothing. The
    # switch is «выключить всё разом», not a second layer of default.
    titles_enabled: Mapped[bool] = mapped_column(Boolean, server_default="true")
    sampling_seconds: Mapped[int] = mapped_column(Integer, server_default="5")
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    def __repr__(self) -> str:
        return f"<AgentSetting(titles_enabled={self.titles_enabled})>"
